### ISSUE TITLE
awesome-javascript

### ISSUE THREAD

**Issue by hueitan** [wwsun/awesome-javascript#1]
你好

供你參考
https://github.com/sorrycc/awesome-javascript

**Comment by wwsun** [comment]
思路不一样吧，这份文档追求的不是罗列JS相关的技术体系，而是那些前沿的、有意思的技术文章的汇总。一个技术名词本身很容易知道，但是一篇优秀的博文其实更值得被发现与分享。

**Comment by hueitan** [comment]
好！
