### ISSUE TITLE
md格式问题

### ISSUE THREAD

**Issue by Lemon7Frank** [wwsun/awesome-javascript#7]
Hi~景庄

本来想在你的文档的基础上加些东西
![image](https://cloud.githubusercontent.com/assets/6349036/10580792/d047d9cc-76b1-11e5-9f61-c7d12d63e86c.png)
fork以后发现加md文档里编辑模式时列表格式有点奇怪，很多前面都是1.
强迫症。。

**Comment by wwsun** [comment]
当涉及到大量的有序列表，切顺序没有最终确定时，源码中使用全1，让解释器自动修成序号。不然，如果要插入一些条目，每次都需要重新更正序号，
- 发自坚果手机 -
  frank <notifications@github.com<mailto:notifications@github.com>> 于 2015年10月19日，下午10:38
  Hi~景庄

本来想在你的文档的基础上加些东西
![image](https://cloud.githubusercontent.com/assets/6349036/10580792/d047d9cc-76b1-11e5-9f61-c7d12d63e86c.png)
fork以后发现加md文档里列表格式有点奇怪，很多前面都是1.
强迫症。。

---

Reply to this email directly or view it on GitHub:
https://github.com/wwsun/awesome-javascript/issues/7

**Comment by Lemon7Frank** [comment]
Get ~ Thx
